server:
  address: 127.0.0.1
  port: 8081
  forward-headers-strategy: native
  tomcat:
    remote-ip-header: X-Real-IP
    protocol-header: X-Forwarded-Proto

spring:
  mvc:
    servlet:
      load-on-startup: 1
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: school
    password: 123456

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  type-handlers-package: indi.xezzon.school.config.typehandler

pagehelper:
  helper-dialect: mariadb
  page-size-zero: true
  reasonable: true
  support-methods-arguments: true

logging:
  level:
    indi.xezzon.school: debug
  file:
    path: log