server:
  port: 9202
spring:
  application:
    name: school-registry
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false