spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=school
    username: school
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    indi.xezzon.school.jwc: debug