server:
  port: 9221
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: X-Real-IP
      protocol-header: X-Forwarded-Proto

spring:
  profiles:
    active: ${TOMCAT_ENV:dev}
  mvc:
    servlet:
      load-on-startup: 1
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  type-handlers-package: indi.xezzon.school.config.typehandler

logging:
  level:
    indi.xezzon.school: debug
  file:
    path: log