spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.9.9:8848
      config:
        server-addr: 192.168.9.9:8848
        file-extension: yaml
  datasource:
    url: jdbc:postgresql://192.168.9.9:5432/school
    username: school
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.9.9
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3000ms
  data:
    mongodb:
      uri: mongodb://school:123456@192.168.9.9:27017/school
