server:
  port: 9222
  servlet:
    context-path: /easm
spring:
  application:
    name: school-eams
  profiles:
    active: ${TOMCAT_ENV:dev}
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations:
    - classpath*:mapper/*Mapper.xml
  type-aliases-package: indi.xezzon.school.common.model
  type-handlers-package: indi.xezzon.school.common.typehandler
  type-enums-package: indi.xezzon.school.common.constant.enums
