server:
  port: 9222
spring:
  application:
    name: school-jwc
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9202/eureka/
    register-with-eureka: true
    fetch-registry: true